services:
  - type: web
    name: safe-backend
    env: node
    rootDir: "Back End/backend"
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_DIALECT
        value: postgres
      - key: DB_REQUIRE_SSL
        value: "true"
      - key: NODE_ENV
        value: production
